server:
  port: 8093

spring:
  application:
    name: movie_review

  # DB config
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
#logging
logging:
  level:
    root: info
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  file:
    path: log